import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
public object Versions {
    public const val com_github_bumptech_glide: String = "4.11.0" // available: "4.12.0"

    public const val com_squareup_retrofit2: String = "2.9.0"

    public const val androidx_databinding: String = "4.1.2"

    public const val org_jetbrains_kotlin: String = "1.4.30"

    public const val androidx_navigation: String = "2.3.3"

    public const val com_google_dagger: String = "2.31.2" // available: "2.32"

    public const val androidx_room: String = "2.2.6"

    public const val com_android_support_test_runner: String = "1.0.2"

    public const val com_android_tools_build_gradle: String = "4.1.2"

    public const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    public const val logging_interceptor: String = "4.9.0" // available: "4.9.1"

    public const val paging_runtime_ktx: String = "3.0.0-alpha13"

    public const val constraintlayout: String = "2.0.4"

    public const val espresso_core: String = "3.0.2"

    public const val recyclerview: String = "1.1.0"

    public const val lint_gradle: String = "27.1.2"

    public const val appcompat: String = "1.2.0"

    public const val material: String = "1.3.0"

    public const val aapt2: String = "4.1.2-6503028"

    public const val junit: String = "4.13.1"

    /**
     * Current version: "6.5"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    public const val gradleLatestVersion: String = "6.8.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
public val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
